# Generated by Django 6.0.7 on 2026-08-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '__first__'),
        ('job_description', '__first__'),
        ('resume', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('location_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Recommended', 'Recommended'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Recommended', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='job_description.jobdescription')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_recommendations', to='resume.resume')),
            ],
            options={
                'verbose_name': 'Job Recommendation',
                'verbose_name_plural': 'Job Recommendations',
                'db_table': 'job_recommendations',
                'ordering': ['-match_score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job')],
            },
        ),
    ]
