# Generated by Django 6.0.7 on 2026-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='OPEN', max_length=50)),
                ('minimum_experience', models.IntegerField(default=0)),
                ('maximum_experience', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('jd_file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('experience_keywords', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'db_table': 'job_descriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
