<<<<<<< HEAD
# Generated by Django 6.1 on 2026-08-10 04:54

import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 6.1 on 2026-08-11 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
>>>>>>> e2ad693 (commit msg)
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('SIGNUP', 'Signup'), ('FORGOT_PASSWORD', 'Forgot Password')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruiter_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='recruiter_o_email_52c538_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
>>>>>>> e2ad693 (commit msg)
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
<<<<<<< HEAD
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='recruiters/profile_images/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='recruiters/company_logos/')),
                ('website', models.URLField(blank=True)),
=======
                ('recruiter_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True)),
                ('company_location', models.CharField(blank=True, max_length=200)),
                ('industry_type', models.CharField(blank=True, max_length=100)),
>>>>>>> e2ad693 (commit msg)
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
<<<<<<< HEAD
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
=======
>>>>>>> e2ad693 (commit msg)
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'Recruiter Profile',
                'verbose_name_plural': 'Recruiter Profiles',
=======
>>>>>>> e2ad693 (commit msg)
                'db_table': 'recruiter_profiles',
                'ordering': ['-created_at'],
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='RecruiterHeaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='recruiters/profile_images/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='recruiters/company_logos/')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('recruiter_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='recruiters.recruiterprofile')),
            ],
            options={
                'db_table': 'recruiter_header_profiles',
            },
        ),
>>>>>>> e2ad693 (commit msg)
    ]
