# Generated by Django 6.1 on 2026-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('role', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('EMPLOYEE', 'Employee'), ('STUDENT', 'Student')], default='CANDIDATE', max_length=50)),
                ('experience', models.IntegerField(default=0, help_text='Experience in years')),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_uploaded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
